---
version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Stockholm
    insecure-external-code-execution: allow
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "06:30"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
