AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'gs1.gemspec'

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false
