AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - lib/gs1/generated_ai_classes.rb

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'gs1.gemspec'

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
